assets/css/custom.css
Change the css style to display class badge.
No breaking changes.
=> Change css style

assets/css/custom.css
=> Change link css style

assets/css/custom.css, assets/js/back-to-top.js, assets/js/flexsearch.js, layouts/_default/list.html, layouts/_default/single.html, layouts/_default/wide.html, layouts/blog/list.html, layouts/blog/single.html, layouts/docs/list.html, layouts/docs/single.html, layouts/head.html, layouts/sidebar.html, layouts/toc.html
=> Copy the theme file to root and add some new css style

content/_index.zh-cn.md
建议把把友链放至顶部栏或者页面底部。首页应该放一些点击率高而不会造成干扰的信息。
=> Remove link of "Links" from the homepage.

.github/workflows/hugo.yaml, content/blog/access-github/index.zh-cn.md, content/docs/sophomore-autumn/EE1011B.md, content/docs/sophomore-autumn/PHYS1002A.md
我不清楚修改 docs 中的 page frontmatter 后我们的 actions 会不会将修改覆盖掉，先试试看？
=> Update on previous post & enable math in some pages

content/_index.zh-cn.md, content/blog/access-github/index.zh-cn.md
如果需要的话，编辑 hugo.yaml 就可以为每一个页面 echo 这个组件。
=> Add license at some pages

content/blog/privileges-with-edu-email/index.zh-cn.md
=> Update post: privileges-with-edu-email

.github/workflows/ci.yaml, README.md, hugo.yaml, scripts/gen_links.py
1. 更新仓库名字
2. 添加部署文档
3. 移除 md 文件在下载页面的显示，目前问题出现在 gen_links.py 执行的时候报错，使 CI 失败，待修复
=> Update editURL base in hugo.yaml, remove .md file extension from gen_links.py

content/blog/privileges-with-edu-email/index.zh-cn.md
之前通过学信网申请 JetBrains 学生许可证成功了，现在把博客更新一下。
如果要修改文章内容，能不能先在这底下的评论里先提一句？
=> update post: applying for JetBrains

.github/workflows/ci.yaml
=> add a new type of course

.github/workflows/ci.yaml, README.md
更新了 CI，应该支持多个 semester 了
tag格式：
semester: aaa / bbb / ccc
=> Support multiple semesters

.github/workflows/ci.yaml
=> Fix the for-loop no ending bug

README-zh.md, README.md
=> Fix some typos in README and add zh-cn version

content/links/index.zh-cn.md
课程回放的链接一直流浪于各种群聊之中难于查找，也没有被搜索引擎收录，所幸在学校官网很容易找到。于是想在本站上新增这个链接，多一个能找到的地方。
=> New link share: 课程回放

.github/workflows/ci.yaml
=> Update ci.yaml to match more repo

.github/workflows/ci.yaml
更新了网站 CI 的周期，并且更改了电子书引导链接的描述
a
=> Update description and cron in ci.yaml

.github/workflows/ci.yaml
=> style: use round brackets in course name

scripts/gen_links.py
=> fix: remove empty boxes

scripts/news_generation.py, scripts/requirements.txt
=> 更新时间跨度，单位变为小时；将显示的时区转为东八区。

scripts/news_generation.py
=> 将显示的时区转为东八区。

scripts/news_generation.py
=> 修复日报周报获取commit时间范围间隔

.github/workflows/course.yaml, scripts/gen_news.py
=> 更新日报为更新速递、更新日报周报生成的格式

content/docs/_index.zh-cn.md
=> Update card titles in _index.zh-cn.md

content/blog/selecting-distributive-lessons/index.zh-cn.md
=> 更新选课指南学时信息，去掉“课外辅导”一列

content/news/daily.md, scripts/gen_news.py
AI 摘要已经比原文字更完整，描述性更好，因此将测试只保留 AI 摘要。
=> feat: only keep AI summary and remove other text

content/blog/how-to-use-FX991CN/index.zh-cn.md
原文略拥挤，故重新排版。添加了一点 “常用技巧” 方面的内容。
=> 重新排版博客《卡西欧 FX-991CNX 计算器使用指南》

.github/workflows/course.yaml, content/docs/general-knowledge/GeneralKnowledge.md, content/docs/general-knowledge/_index.zh-cn.md, content/docs/junior-spring/AUTO3001B.md, content/news/daily.md
=> Update course.yaml - add GeneralKnowledge as a course

layouts/shortcodes/hero-container.html
=> restore normal homepage

layouts/partials/components/giscus.html
=> fix: giscus theme not switched correctly

layouts/partials/navbar.html
=> fix: wrong navbar at mobile device

.github/workflows/course.yaml, assets/css/custom.css, scripts/fetch_opened_prs_and_issues.py
- 移除 custom.css 中的过时代码
- 修复 https://github.com/HITSZ-OpenAuto/hoa-moe/issues/207 中提到的高度跳变问题，使用 width 替代 scaleX
- 当导航栏选中后，颜色变深，增强视觉效果
- 移除 GitHub logo 旋转（个人觉得没什么必要添加一个旋转）
=> fix: enhance link animations and adjust hover effects

content/news/daily.md
=> feat: stats module in news module

assets/css/custom.css
参考以下页面增加了阴影和卡片缩放比例
- <https://www.apple.com/store>
| 修改前                                                       | 修改后                                                       |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| ![Screenshot 2024-12-25 at 11 15 03 PM](https://github.com/user-attachments/assets/871f0e81-c3a5-44b6-b638-e134ac55e19f) | ![image](https://github.com/user-attachments/assets/2c76daaa-2923-4d11-92bf-57fb2f6ed70c) |
=> style: add shadow to hextra feature card

assets/css/custom.css
- 新增文章内链接下划线样式，hover 时改变下划线颜色，增加视觉反馈
- 链接样式参考 https://cs186berkeley.net/
=> feat: add article link style(solid underline)

content/blog/how-to-use-FX991CN/index.zh-cn.md
更新了 991CN 的使用说明
- 将文字格式统一抽离出 <style> 方便管理
- 新增 计算传函的分离点并验证是否存在 部分
- 添加了一些在阅读时容易被忽略的注意事项，如某一个功能需要在计算器的某个特定的模式下才能运行
=> update 991CN usage instructions

.github/workflows/course-single.yaml, .github/workflows/course.yaml, content/docs/cross-specialty/_index.zh-cn.md, content/docs/general-knowledge/_index.zh-cn.md, content/docs/graduate-autumn/_index.zh-cn.md, content/docs/graduate-spring/_index.zh-cn.md, content/news/daily.md
=> 更新 course.yaml 和 course-single.yaml - 新增“本研共通”、“选修”课程类型和研究生学期

assets/css/compiled/main.css, layouts/shortcodes/hoa-filetree/folder.html, scripts/gen_links.py
- remove the folder date
- change to GraphQL api
=> fix: change gen_links scripts to avoid workflow bugs

content/links/index.zh-cn.md
=> docs: add link to hitsz-connect-verge

.github/workflows/course-single.yaml, .github/workflows/course.yaml, layouts/shortcodes/hoa-filetree/folder.html, scripts/gen_links.py
- 重构了 workflow，让 gen_links 对所有仓库异步运行
=> feat: refactor gen_links.py to shorten runtime

scripts/gen_links.py
- 修复环境变量名 typo
- 剔除文件树中所有 README.md 文件，减少查询次数
=> fix: Build Single Page script error

assets/css/compiled/main.css, assets/css/custom.css, layouts/shortcodes/hoa-filetree/container.html, scripts/gen_links.py
=> feat: add no file fallback

assets/css/custom.css, content/_index.zh-cn.md
- https://github.com/HITSZ-OpenAuto/hoa-moe/issues/237
- https://github.com/HITSZ-OpenAuto/hoa-moe/issues/238
=> fix: filetree darkmode and card link

content/blog/contribution-guide/_index.zh-cn.md, content/blog/writing-rules/index.zh-cn.md, layouts/shortcodes/hoa-filetree/container.html
- 更新标题为《参与指南》，与 Org 下其他地方统一表述
- 隐藏上一份《参与指南》
=> docs: update title of contribution guide

assets/css/compiled/main.css, assets/js/file-check.js, layouts/shortcodes/hoa-filetree/container.html
=> fix: incorrect link element modify

content/links/index.zh-cn.md
=> docs: add CityU friend link

scripts/courses/build_course_pages.py
现在已经没有以 ’研究生阶段课程‘ 作为 category 的课程了。
@MaxwellJay256 @longlin10086 @IcyDesert @WDGaster703 @YinMo19
=> delete the obsolete tag '研究生阶段课程'

.github/workflows/course.yaml, .gitignore
#262 
自动格式化有助于保持整个仓库统一和谐的代码风格。[ruff](https://github.com/astral-sh/ruff) 是一个基于 rust 的 python 格式化工具，可以集成进 action 中对 python 代码自动格式化，十分方便。
加上后的效果可以见我的 repo 的一个 [commit](https://github.com/pspdada/hoa-moe/commit/18ab199fb17abf5619dc34def621df600a0a5dcc)，后续若有规范的格式需求，可建立一个 `ruff.toml` 指定风格。
@longlin10086
=> Enhancement: add auto format

content/news/daily.md, scripts/courses/fetch_opened_prs_and_issues.py
News on issues and prs use UTC time by default, which feels odd for Chinese readers:
```
仓库: MATH1002
创建于: 2025-01-20T07:32:37Z
```
It would be more convenient to read if converted to Beijing time.
```
仓库: MATH1002
创建于: 2025-01-20 15:32:37
```
=> feat: use Beijing time for issues and prs' created time

content/blog/using-hitsz-connect-verge-to-ssh-school-server/index.zh-cn.md
=> docs: update blog about school server

content/blog/contribution-guide/_index.zh-cn.md, content/blog/contribution-guide/edit-multi-docs-and-upload-files/index.zh-cn.md, content/blog/contribution-guide/edit-single-file-and-upload-file/index.zh-cn.md, content/blog/contribution-guide/write-blogs/index.zh-cn.md
参照 Go 入门文档 https://go.dev/doc/tutorial/call-module-code
=> feat: 添加预备知识指示

assets/css/compiled/main.css, assets/css/custom.css, assets/js/file-download.js, layouts/shortcodes/hoa-filetree/container.html
Add a toggle switch for enabling campus network download acceleration. Includes:
- New checkbox UI component in filetree container
- CSS styles for the toggle switch
- JS logic to handle toggle state and URL modification
- Persist toggle state in localStorage
目前是直接对 url 做了一个替换
由于 preview 的 url 写在 a 标记的 href 里了，所以 preview 没有做加速
ps: 我是不是应该用 acceleration 的
=> feat: add campus network download acceleration toggle

content/news/future-of-hoa/index.zh-cn.md
- 将 HOA 的招新博客移至新闻栏目
- 更新标题
@OliverWu515
=> blog: update categories of future of hoa
